baseURL = "https://test.ijam.it"
title = "iJam IT B.V."
#author = "username"
languageCode = "nl"
DefaultContentLanguage = "nl"
enableInlineShortcodes = true
theme = ["hugo-cloak-email", "tella"]
enableRobotsTXT = true
cleanDestinationDir = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = ['vacatures']
  googleFonts = true

  [params.logo]
    main = "img/logo/logo.png"
    alt = "iJam IT Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-32"

  [params.site]
    name = "iJam IT B.V."

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "labels"
    name = "Labels"
    url = "/labels/"
    weight = 2

  [[menu.main]]
    identifier = "team"
    name = "The Team"
    url = "/team/"
    weight = 3

  [[menu.main]]
    identifier = "vacatures"
    name = "Vacatures"
    url = "/vacatures/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1
